### ISSUE TITLE
Perms not working correctly

### ISSUE THREAD

**Issue by baticag** [magnusulf/Factions#43] opened 2019-07-10 13:04 UTC
You can give certain perms to ranks in factions, but once they are given to ranks they cannot be revoked. It shows correctly that you removed perm, also the perm doesn't show up in perms list for specific rank, but players with that rank can still do stuff like they have that perm.

**Comment by baticag** [comment] 2019-07-17 19:15
Any news about this problem?

**Comment by magnusulf** [comment] 2019-08-11 14:41
Could not be reproduced. Probably duplicate of #40.

**Closed as completed by magnusulf** 2019-08-11 14:41 UTC
