### ISSUE TITLE
Can't retrieve Loyalty III tridents fired at allies

### ISSUE THREAD

**Issue by Ferocimo** [magnusulf/Factions#34] opened 2019-05-14 16:10 UTC
## Affected Plugin
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.5

## Describe your Environment
- **Server Version:** git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

## Steps to Reproduce this Bug
1. Have two players connected, both in different factions. Player A and player B.
2. Have them be allied to each other.
3. Player A is equipped with a trident enchanted Loyalty III.
4. Player A fires his trident on his ally, player B.

## Observed Results
Player A gets the message "you can't hurt allies" and the trident disappears (it is NOT dropped, it disappears).

## Expected Results
Trident should come back to player A, much like when you fire a trident to a gamemode 1 person.

Thank you for looking into this.

**Comment by magnusulf** [comment] 2019-05-19 21:41
I can't reproduce this on version 3.2.2 (the latest version). Could you try to see if it still happens on version 3.2.2?

**Comment by magnusulf** [comment] 2019-05-19 22:00
I did some more testing. It does happen on 1.13.2 (at least with paperspigot) but it does not happen on 1.14. I suspect the bug might not be with Spigot and not Factions but I am not sure.

**Comment by magnusulf** [comment] 2019-05-19 22:24
Anyway I think it is fixed now and will be included in the next release. The bug was probably in Factions.

**Closed as completed** 2019-05-19 22:24 UTC

**Comment by Ferocimo** [comment] 2019-05-20 16:42
@magnusulf I'm not sure I get it, do you mean you fixed it for 1.13, or that it will only be fixed in 1.14 ?

**Comment by magnusulf** [comment] 2019-05-20 19:56
It _is_ fixed for 1.14. The bug never occurred on 1.14. It will however be fixed for 1.13 in the next update.

**Comment by Ferocimo** [comment] 2019-05-21 10:27
Okay thank you for your time !

**Comment by Ferocimo** [comment] 2019-06-26 18:10
@magnusulf So, when will the next 1.13 update with this fix be ?
